config/routes.rb
Playlist::Application.routes.draw do
  resources :roles

  devise_for :users
  resources :users
  get "home/index"
  resources :musicas
  match '/my' => 'musicas#my_musics'

  root :to => 'musicas#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user

    if user.role? :administrator
      can :manage, :all
    elsif user.role? :operator
      can :manage, Musica
    else
      can :read, :all
    end
  end
end

app/models/musica.rb
class Musica < ActiveRecord::Base
  belongs_to :user
  attr_accessible :autor, :nome, :user_id
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name, :id , :role_ids
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :musicas
  has_and_belongs_to_many :roles
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_ids, :user_id
  # attr_accessible :title, :body

  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    redirect_to root_url
  end
end

app/controllers/musicas_controller.rb
class MusicasController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /musicas
  # GET /musicas.json
  def index
    @musicas = Musica.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @musicas }
    end
  end

  # GET /musicas/1
  # GET /musicas/1.json
  def show
    @musica = Musica.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @musica }
    end
  end

  def my_musics
    @musics = Musica.where(:user_id => current_user.id)

    respond_to do |format|
      format.html
      format.json{ render json: @musica }
    end
  end

  # GET /musicas/new
  # GET /musicas/new.json
  def new
    @musica = Musica.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @musica }
    end
  end

  # GET /musicas/1/edit
  def edit
    @musica = Musica.find(params[:id])
  end

  # POST /musicas
  # POST /musicas.json
  def create
    @musica = Musica.new(params[:musica])
    @musica.user_id = current_user.id
    respond_to do |format|
      if @musica.save
        format.html { redirect_to @musica, notice: 'Musica was successfully created.' }
        format.json { render json: @musica, status: :created, location: @musica }
      else
        format.html { render action: "new" }
        format.json { render json: @musica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /musicas/1
  # PUT /musicas/1.json
  def update
    @musica = Musica.find(params[:id])

    respond_to do |format|
      if @musica.update_attributes(params[:musica])
        format.html { redirect_to @musica, notice: 'Musica was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @musica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musicas/1
  # DELETE /musicas/1.json
  def destroy
    @musica = Musica.find(params[:id])
    @musica.destroy

    respond_to do |format|
      format.html { redirect_to musicas_url }
      format.json { head :no_content }
    end
  end
  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "playlist" && password == "playlist"
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    @current_method = "new"

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/musicas_helper.rb
module MusicasHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playlist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Playlist</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li><a href="/musicas">Musicas</a></li>
            <% if user_signed_in? %>
            <li>
              <%= link_to 'Minhas Musicas', :controller => 'musicas', :action => 'my_musics' %>
            </li>
            <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </li>
            <% else %>
            <li>
              <%= link_to('Login', new_user_session_path)  %>
            </li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <div class="container">
    <% flash.each do |key, value| %>

    <div class="flash <%= key %>">
      <%= value %>
    </div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/musicas/_form.html.erb
<%= form_for(@musica) do |f| %>
  <% if @musica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@musica.errors.count, "error") %> prohibited this musica from being saved:</h2>

      <ul>
      <% @musica.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <%= f.hidden_field :user_id %>
  <div class="actions">
    <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/musicas/edit.html.erb
<h1>Editing musica</h1>

<%= render 'form' %>

<%= link_to 'Show', @musica %> |
<%= link_to 'Back', musicas_path %>

app/views/musicas/index.html.erb
<h1>Listing musicas</h1>

<table class="table">
  <tr>
    <th>Nome</th>
    <th>Autor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @musicas.each do |musica| %>
  <tr>
    <td><%= musica.nome %></td>
    <td><%= musica.autor %></td>
    <% if current_user.id == musica.user_id %>
      <td><%= link_to 'Mostrar', musica %></td>
      <td><%= link_to 'Editar', edit_musica_path(musica) %></td>
      <td><%= link_to 'Apagar', musica, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nova Musica', new_musica_path, :class => 'btn btn-primary' %>

app/views/musicas/my_musics.html.erb
<h1>Minhas musicas</h1>

<table class="table">
  <tr>
    <th>Nome</th>
    <th>Autor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @musics.each do |musica| %>
  <tr>
    <td><%= musica.nome %></td>
    <td><%= musica.autor %></td>
    <% if current_user.id == musica.user_id %>
      <td><%= link_to 'Mostrar', musica %></td>
      <td><%= link_to 'Editar', edit_musica_path(musica) %></td>
      <td><%= link_to 'Apagar', musica, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nova Musica', new_musica_path, :class => 'btn btn-primary' %>

app/views/musicas/new.html.erb
<h1>New musica</h1>

<%= render 'form' %>

<%= link_to 'Back', musicas_path %>

app/views/musicas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @musica.nome %>
</p>

<p>
  <b>Autor:</b>
  <%= @musica.autor %>
</p>


<%= link_to 'Edit', edit_musica_path(@musica) %> |
<%= link_to 'Back', musicas_path %>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td><%= link_to 'Show', role %></td>
    <td><%= link_to 'Edit', edit_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @role.name %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :username %><br />
  <%= f.text_field :username %>
</div>
<% if @current_method == "new" %>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %>
</div>
<% for role in Role.find(:all) %>
<div>
  <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
  <%= role.name %>
</div>
<% end %>
<% end %>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Username</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.username %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New user', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>